{{/*
Return the kong api gateway configuration for the given environment.

Parameters:
- global: The global values
- apiGateway: The api gateway values

Example:
{{ include "czertainly-lib.api-gateway.kong.yaml" ( dict "global" .Values.global "apiGateway" .Values ) }}
*/}}
{{- define "czertainly-lib.api-gateway.kong.yaml" -}}
{{- $hostName := pluck "hostName" .global .apiGateway | compact | first }}
kong.yml: |-
  _format_version: '2.1'
  _transform: true
  services:
    - name: protocols
      host: {{ .apiGateway.backend.core.service.name }}
      port: {{ .apiGateway.backend.core.service.port }}
      protocol: http
      routes:
        - name: protocols_route
          strip_path: false
          preserve_host: true
          paths:
            - {{ .apiGateway.backend.core.service.apiUrl}}/v1/protocols
    - name: core
      host: {{ .apiGateway.backend.core.service.name }}
      port: {{ .apiGateway.backend.core.service.port }}
      protocol: http
      routes:
        - name: core_route-cert
          strip_path: false
          preserve_host: true
          paths:
            - {{ .apiGateway.backend.core.service.apiUrl}}
          headers:
            ssl-client-cert:
              - ~*(.*?)
          plugins:
            - name: request-transformer
              config:
                rename:
                  headers:
                    - '{{ .apiGateway.auth.header.cert.downstream }}:{{ .apiGateway.auth.header.cert.upstream }}'
        {{- if or .global.keycloak.enabled .apiGateway.oidc.enabled }}
        - name: core_route-oidc
          strip_path: false
          preserve_host: true
          paths:
            - {{ .apiGateway.backend.core.service.apiUrl}}
        {{- end }}
    {{- if or .global.keycloak.enabled .apiGateway.oidc.enabled }}
    - name: core-oauth2
      host: {{ .apiGateway.backend.core.service.name }}
      port: {{ .apiGateway.backend.core.service.port }}
      protocol: http
      path: /api
      routes:
        - name: core-oauth2_route
          strip_path: false
          preserve_host: true
          paths:
            - {{ .apiGateway.backend.fe.service.loginUrl}}
            - {{ .apiGateway.backend.fe.service.logoutUrl}}
    {{- end }}
    - name: fe-administrator
      host: {{ .apiGateway.backend.fe.service.name}}
      port: {{ .apiGateway.backend.fe.service.port }}
      protocol: http
      routes:
        - name: fe-administrator_route-cert
          preserve_host: true
          strip_path: true
          paths:
            - {{ .apiGateway.backend.fe.service.baseUrl}}
          headers:
            ssl-client-cert:
              - ~*(.*?)
          plugins:
            - name: request-transformer
              config:
                rename:
                  headers:
                    - '{{ .apiGateway.auth.header.cert.downstream }}:{{ .apiGateway.auth.header.cert.upstream }}'
        {{- if or .global.keycloak.enabled .apiGateway.oidc.enabled }}
        - name: fe-administrator_route
          strip_path: true
          preserve_host: true
          paths:
            - {{ .apiGateway.backend.fe.service.baseUrl}}
        {{- end }}
    {{- if or .global.keycloak.enabled }}
    - name: keycloak-internal-service
      host: keycloak-internal-service
      port: 8080
      routes:
        - name: keycloak
          strip_path: false
          preserve_host: true
          paths:
            - /kc
    {{- end }}
    {{- if or .global.messaging.remoteAccess }}
    - name: messaging-service
      host: messaging-service
      port: 15672
      routes:
        - name: rabbitmq
          strip_path: true
          preserve_host: true
          paths:
            - /mq
    {{- end }}
    {{- if or .global.utils.enabled }}
    - name: utils-service-service
      host: utils-service-service
      port: 8080
      routes:
        - name: v1-utils-route
          strip_path: true
          preserve_host: true
          paths:
            - /utils
    {{- end }}
  {{- if .apiGateway.cors.enabled }}
  plugins:
    - name: cors
      config:
        origins: {{ toYaml .apiGateway.cors.origins | nindent 8 }}
        credentials: true
        max_age: 3600
        exposed_headers: {{ toYaml .apiGateway.cors.exposedHeaders | nindent 8 }}
        preflight_continue: false
  {{- end }}
{{- end }}