apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - '/bin/sh'
      - '-c'
      - 'printf ">%s<\n" $@; sleep 36000'
    args:
      - 'first_argument'
      - 'second_argument'
      - 'third_argument'



