annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.5.0
name: network-discovery-provider
description: A Helm chart for Network Discovery Provider for CZERTAINLY platform.
home: https://github.com/CZERTAINLY/CZERTAINLY-IP-Discovery-Provider
icon: https://github.com/CZERTAINLY/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
dependencies:
  - name: czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../czertainly-lib
    version: 1.3.0
keywords:
  - czertainly
  - trust
  - management
  - lifecycle
  - platform
  - network
  - discovery
  - provider
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/CZERTAINLY/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/CZERTAINLY/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 1.5.0
