apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-internal-configmap
data:
  czertainly_realm.json: |-
{{- tpl (.Files.Get "czertainly_realm.json") . | indent 4 }}
{{- if .Values.createDbSchema }}
  create_schema.sh: |-
{{- tpl (.Files.Get "create_schema.sh") . | indent 4 }}
{{- end }}