apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-internal-configmap
data:
  czertainly_realm.json: |-
    {{- tpl (.Files.Get "realms/czertainly-2.14.0_realm.json") . | indent 4 }}
  create_schema.sh: |-
    {{- tpl (.Files.Get "create_schema.sh") . | indent 4 }}
