apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-internal-configmap
data:
  ilm_realm.json: |-
    {{- tpl (.Files.Get "realms/ilm-2.17.0_realm.json") . | indent 4 }}
  create_schema.sh: |-
    {{- tpl (.Files.Get "create_schema.sh") . | indent 4 }}
