annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.1.6
name: pyadcs-connector
description: A Helm chart for PyADCS Connector for ILM platform.
home: https://github.com/OmniTrustILM/ilm
icon: https://github.com/OmniTrustILM/ilm/icon/ot-icon-color.svg
dependencies:
  - name: ilm-lib
    # repository: oci://hub.omnitrustregistry.com/ilm-helm
    repository: file://../ilm-lib
    version: 1.4.2-1-develop
keywords:
  - ilm
  - trust
  - management
  - lifecycle
  - platform
  - pyadcs
  - authority
  - discovery
  - provider
maintainers:
  - name: OmniTrustILM
    email: ilm@omnitrust.com
    url: https://github.com/OmniTrustILM/helm-charts
type: application
sources:
  - https://github.com/OmniTrustILM/ilm
  - https://omnitrust.com
  - https://docs.otilm.com
version: 1.1.6-1-develop
