annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 3.9.1
name: api-gateway-kong
description: A Helm chart for API Gateway based on the Kong for ILM platform.
home: https://github.com/OmniTrustILM/ilm
icon: https://github.com/OmniTrustILM/ilm/icon/ot-icon-color.svg
dependencies:
  - name: ilm-lib
    # repository: oci://hub.omnitrustregistry.com/ilm-helm
    repository: file://../ilm-lib
    version: 1.4.2-1-develop
keywords:
  - ilm
  - trust
  - management
  - lifecycle
  - platform
  - api
  - gateway
maintainers:
  - name: OmniTrustILM
    email: ilm@omnitrust.com
    url: https://github.com/OmniTrustILM/helm-charts
type: application
sources:
  - https://github.com/OmniTrustILM/ilm
  - https://omnitrust.com
  - https://docs.otilm.com
  - https://github.com/revomatico/docker-kong-oidc
  - https://github.com/revomatico/kong-oidc
version: 3.9.1-2-develop
