{{- if not .Values.global.config.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: caching-secret-{{ .Chart.Name | lower }}
  labels:
    {{- include "caching-valkey.labels" . | nindent 4 }}
data:
  valkey.password: {{ pluck "password" .Values.global.valkey .Values.valkey | compact | first | default "" | b64enc | quote }}
{{- end }}
