apiVersion: v1
data:
  # if the global values are defined, use it, otherwise use local values
  {{- if .Values.global.database.pgBouncer.enabled }}
  database_host: {{ .Values.global.database.pgBouncer.host | b64enc | quote }}
  database_port: {{ .Values.global.database.pgBouncer.port | toString | b64enc | quote }}
  {{- else }}
  database_host: {{ pluck "host" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  database_port: {{ pluck "port" .Values.global.database .Values.database | compact | first | toString | b64enc | quote }}
  {{- end }}
  database_name: {{ pluck "name" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  database_user: {{ pluck "username" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  database_password: {{ pluck "password" .Values.global.database .Values.database | compact | first | b64enc | quote }}
kind: Secret
metadata:
  name: ct-logs-discovery-provider-secret
