{{- $httpProxy := pluck "httpProxy" .Values.global .Values | compact | first }}
{{- $httpsProxy := pluck "httpsProxy" .Values.global .Values | compact | first }}
{{- $noProxy := pluck "noProxy" .Values.global .Values | compact | first }}
{{- $additionalInitContainers := (include "ct-logs-discovery-provider.customization.initContainers" $) }}
{{- $additionalSidecarContainers := (include "ct-logs-discovery-provider.customization.sidecarContainers" $) }}
{{- $additionalVolumes := (include "ct-logs-discovery-provider.customization.volumes" $) }}
{{- $additionalVolumeMounts := (include "ct-logs-discovery-provider.customization.volumeMounts" $) }}
{{- $additionalEnv := (include "ct-logs-discovery-provider.customization.env" $) }}
{{- $additionalEnvFrom := (include "ct-logs-discovery-provider.customization.envFrom" $) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-logs-discovery-provider-deployment
  labels:
    {{- include "ct-logs-discovery-provider.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ct-logs-discovery-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ct-logs-discovery-provider.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "ct-logs-discovery-provider.imagePullSecrets" . | indent 6 }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- .Values.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      {{- if $additionalInitContainers }}
      initContainers:
        {{- $additionalInitContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: ct-logs-discovery-provider
          image: {{ include "ct-logs-discovery-provider.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: ct-logs-discovery-provider-secret
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: ct-logs-discovery-provider-secret
                  key: database_port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: ct-logs-discovery-provider-secret
                  key: database_name
            - name: DATABASE_SCHEMA
              value: {{ .Values.database.schema | quote }}
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: ct-logs-discovery-provider-secret
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ct-logs-discovery-provider-secret
                  key: database_password
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            {{- if $httpProxy }}
            - name: HTTP_PROXY
              value: {{ $httpProxy }}
            {{- end }}
            {{- if $httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ $httpsProxy }}
            {{- end }}
            {{- if $noProxy }}
            - name: NO_PROXY
              value: {{ $noProxy }}
            {{- end }}
            {{- if $additionalEnv }}
              {{- $additionalEnv | nindent 12 }}
            {{- end }}
          {{- if $additionalEnvFrom }}
          envFrom:
            {{- $additionalEnvFrom | indent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.image.securityContext }}
          securityContext: {{- .Values.image.securityContext | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.image.probes.liveness.enabled }}
          livenessProbe:
            {{- if .Values.image.probes.liveness.custom }}
            {{- toYaml .Values.image.probes.liveness.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: /v1/health
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.image.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.image.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.image.probes.liveness.periodSeconds }}
            successThreshold: {{ .Values.image.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.image.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.image.probes.readiness.enabled }}
          readinessProbe:
            {{- if .Values.image.probes.readiness.custom }}
            {{- toYaml .Values.image.probes.readiness.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: /v1/health
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.image.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.image.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.image.probes.readiness.periodSeconds }}
            successThreshold: {{ .Values.image.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.image.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.image.probes.startup.enabled }}
          startupProbe:
            {{- if .Values.image.probes.startup.custom }}
            {{- toYaml .Values.image.probes.startup.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: /v1/health
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.image.probes.startup.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.image.probes.startup.timeoutSeconds }}
            periodSeconds: {{ .Values.image.probes.startup.periodSeconds }}
            successThreshold: {{ .Values.image.probes.startup.successThreshold }}
            failureThreshold: {{ .Values.image.probes.startup.failureThreshold }}
          {{- end }}
          {{- if .Values.image.resources }}
          resources: {{- toYaml .Values.image.resources | nindent 12 }}
          {{- end }}
          {{- if or .Values.global.trusted.certificates .Values.trusted.certificates $additionalVolumeMounts }}
          volumeMounts:
            {{- if or .Values.global.trusted.certificates .Values.trusted.certificates }}
            - name: trusted-certificates-volume
              mountPath: /etc/ssl/certs/ca.crt
              subPath: ca.crt
              readOnly: true
            {{- end }}
            {{- if $additionalVolumeMounts }}
              {{- $additionalVolumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
        {{- if $additionalSidecarContainers }}
          {{- $additionalSidecarContainers | nindent 8 }}
        {{- end }}
      {{- if or .Values.global.trusted.certificates .Values.trusted.certificates $additionalVolumes }}
      volumes:
        {{- if .Values.global.trusted.certificates }}
        - name: trusted-certificates-volume
          secret:
            defaultMode: 420
            secretName: trusted-certificates
        {{- else if .Values.trusted.certificates }}
        - name: trusted-certificates-volume
          secret:
            defaultMode: 420
            secretName: trusted-certificates-{{ .Chart.Name | lower }}
        {{- end }}
        {{- if $additionalVolumes }}
          {{- $additionalVolumes | nindent 8 }}
        {{- end }}
      {{- end }}