{{- if .Values.global.provisioning.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: provisioning-secret
data:
  provisioningApiKey: {{ .Values.global.provisioning.apiKey | b64enc | quote }}
{{- end }}
