annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.0.0
name: provisioning-rabbitmq
description: A Helm chart for RabbitMQ provisioning service for ILM platform.
home: https://github.com/OmniTrustILM/ilm
icon: https://raw.githubusercontent.com/OmniTrustILM/ilm/main/icon/ot-icon-color.svg
dependencies:
  - name: ilm-lib
    # repository: oci://hub.omnitrustregistry.com/ilm-helm
    repository: file://../ilm-lib
    version: 1.4.2-1-develop
keywords:
  - ilm
  - trust
  - management
  - lifecycle
  - platform
  - rabbitmq
  - provisioning
maintainers:
  - name: OmniTrustILM
    email: ilm@omnitrust.com
    url: https://github.com/OmniTrustILM/helm-charts
type: application
sources:
  - https://github.com/OmniTrustILM/ilm
  - https://omnitrust.com
  - https://docs.otilm.com
version: 1.0.0-develop
