{{- $valkeyEnabled := or .Values.cachingService.enabled .Values.global.valkey.external.enabled }}
{{- if $valkeyEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: caching-secret
data:
  {{- if .Values.global.valkey.external.enabled }}
  valkey.password: {{ .Values.global.valkey.password | default "" | b64enc | quote }}
  {{- else }}
  valkey.password: {{ pluck "password" .Values.global.valkey .Values.cachingService.valkey | compact | first | default "" | b64enc | quote }}
  {{- end }}
{{- end }}
