{{- if not .Values.global.config.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: messaging-secret
data:
  messaging.username: {{ pluck "username" .Values.global.messaging .Values.messaging | compact | first | b64enc | quote }}
  messaging.password: {{ pluck "password" .Values.global.messaging .Values.messaging | compact | first | b64enc | quote }}
{{- end }}
