CREATE USER ilmuser WITH PASSWORD 'your-strong-password';
CREATE DATABASE ilmdb ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' TEMPLATE=template0;
GRANT ALL PRIVILEGES ON DATABASE ilmdb to ilmuser;
