annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.0.1
name: scheduler-service
description: A Helm chart for CZERTAINLY platform Scheduler service.
home: https://github.com/CZERTAINLY/CZERTAINLY-Scheduler
icon: https://github.com/CZERTAINLY/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
dependencies:
  - name: czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../czertainly-lib
    version: 1.3.0
  - name: messaging-rabbitmq
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../messaging-rabbitmq
    tags:
      - messaging
    version: 3.12.1-2
    condition: messaging.local
keywords:
  - czertainly
  - trust
  - management
  - lifecycle
  - platform
  - software
  - scheduler
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/CZERTAINLY/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/CZERTAINLY/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 1.0.1
