{{- if not .Values.global.config.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: messaging-secret
stringData:
  messaging.username: {{ pluck "username" .Values.global.messaging .Values.messaging | compact | first }}
  messaging.password: {{ pluck "password" .Values.global.messaging .Values.messaging | compact | first }}
  messaging.cookie: {{ .Values.messaging.erlang.cookie }}
  messaging.definitions.json: |-
    {{- include "messaging-rabbitmq.definitions.json" (dict "global" .Values.global "messagingService" .Values) | indent 4 }}
{{- end }}
