{{- $additionalPorts := (include "webhook-notification-provider.customization.ports" $) }}
apiVersion: v1
kind: Service
metadata:
  name: webhook-notification-provider-service
  labels:
    {{- include "webhook-notification-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
    {{- if $additionalPorts }}
      {{- $additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "webhook-notification-provider.selectorLabels" . | nindent 4 }}
