_format_version: '2.1'
_transform: true
services:
  - name: protocols
    host: {{ .Values.backend.core.service.name }}
    port: {{ .Values.backend.core.service.port }}
    protocol: http
    routes:
      - name: protocols_route
        strip_path: false
        preserve_host: true
        paths:
          - {{ .Values.backend.core.service.apiUrl}}/v1/protocols
  - name: core
    host: {{ .Values.backend.core.service.name }}
    port: {{ .Values.backend.core.service.port }}
    protocol: http
    routes:
      - name: core_route-cert
        strip_path: false
        preserve_host: true
        paths:
          - {{ .Values.backend.core.service.apiUrl}}
        headers:
          ssl-client-cert:
            - ~*(.*?)
        plugins:
          - name: request-transformer
            config:
              rename:
                headers:
                  - '{{ .Values.auth.header.cert.downstream }}:{{ .Values.auth.header.cert.upstream }}'
      {{- if or .Values.global.keycloak.enabled .Values.oidc.enabled }}
      - name: core_route-oidc
        strip_path: false
        preserve_host: true
        paths:
          - {{ .Values.backend.core.service.apiUrl}}
      {{- end }}
  {{- if or .Values.global.keycloak.enabled .Values.oidc.enabled }}
  - name: core-login
    host: {{ .Values.backend.core.service.name }}
    port: {{ .Values.backend.core.service.port }}
    protocol: http
    path: /api
    routes:
      - name: core-login_route
        strip_path: false
        preserve_host: true
        paths:
          - {{ .Values.backend.fe.service.loginUrl}}
          - {{ .Values.backend.fe.service.logoutUrl}}
  {{- end }}
  - name: fe-administrator
    host: {{ .Values.backend.fe.service.name}}
    port: {{ .Values.backend.fe.service.port }}
    protocol: http
    routes:
      - name: fe-administrator_route-cert
        preserve_host: true
        strip_path: true
        paths:
          - {{ .Values.backend.fe.service.baseUrl}}
        headers:
          ssl-client-cert:
            - ~*(.*?)
        plugins:
          - name: request-transformer
            config:
              rename:
                headers:
                  - '{{ .Values.auth.header.cert.downstream }}:{{ .Values.auth.header.cert.upstream }}'
      {{- if or .Values.global.keycloak.enabled .Values.oidc.enabled }}
      - name: fe-administrator_route
        strip_path: true
        preserve_host: true
        paths:
          - {{ .Values.backend.fe.service.baseUrl}}
      {{- end }}
  {{- if or .Values.global.keycloak.enabled }}
  - name: keycloak-internal-service
    host: keycloak-internal-service
    port: 8080
    routes:
      - name: keycloak
        strip_path: false
        preserve_host: true
        paths:
          - /kc
  {{- end }}
  {{- if or .Values.global.messaging.remoteAccess }}
  - name: messaging-service
    host: messaging-service
    port: 15672
    routes:
      - name: rabbitmq
        strip_path: true
        preserve_host: true
        paths:
          - /mq
  {{- end }}
  {{- if or .Values.global.utils.enabled }}
  - name: utils-service-service
    host: utils-service-service
    port: 8080
    routes:
      - name: v1-utils-route
        strip_path: true
        preserve_host: true
        paths:
          - /utils
  {{- end }}
{{- if .Values.cors.enabled }}
plugins:
  - name: cors
    config:
      origins: {{ toYaml .Values.cors.origins | nindent 8 }}
      credentials: true
      max_age: 3600
      exposed_headers: {{ toYaml .Values.cors.exposedHeaders | nindent 8 }}
      preflight_continue: false
{{- end }}